language: php
php:
    - 7.3
    - 7.4

env:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-stable"
    - COMPOSER_ARGS="--prefer-stable --prefer-lowest"

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.3
            script:
                - vendor/bin/phpcs
        -   stage: Code Coverage
            php: 7.3
            script:
                - vendor/bin/tester -s -p phpdbg -c tests/php.ini tests --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
                - php php-coveralls.phar --verbose --config tests/coveralls.yml
    allow_failures:
        -   stage: Code Coverage

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_ARGS

script:
    - vendor/bin/parallel-lint -e php,phpt --exclude tests/temp src tests
    - vendor/bin/tester -s -p php -c tests/php.ini tests
    - vendor/bin/phpstan.phar analyse
    - vendor/bin/phpstan.phar analyse -c phpstan.tests.neon.dist

after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find tests -name \*.expected); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
